spring:
  datasource:
    url: jdbc:postgresql://rut-psql-lab:5432/food_delivery
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.flywaydb: DEBUG

server:
  port: 8080