name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Checkstyle (Linter)
        run: mvn checkstyle:check

      - name: Run Tests with JUnit 5
        run: mvn test

